steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    env:
      - 'NEXT_PUBLIC_API_KEY=${_NEXT_PUBLIC_API_KEY}'
      - 'NEXT_PUBLIC_AUTH_DOMAIN=${_NEXT_PUBLIC_AUTH_DOMAIN}'
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - 'NEXT_PUBLIC_STORAGE_BUCKET=${_NEXT_PUBLIC_STORAGE_BUCKET}'
      - 'NEXT_PUBLIC_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_MESSAGING_SENDER_ID}'
      - 'NEXT_PUBLIC_APP_ID=${_NEXT_PUBLIC_APP_ID}'
      - 'NEXT_PUBLIC_MEASUREMENT_ID=${_NEXT_PUBLIC_MEASUREMENT_ID}'